[network]
listen_addresses = [
  "/ip4/127.0.0.1/tcp/8446/ws",
]
seed_nodes = [
  { address = "/ip4/127.0.0.1/tcp/8443/ws" },
]
allow_loopback_addresses = true
desired_peer_count = 1
peer_key_file = "./tmp/.nimiq3/peer_key.dat"

[consensus]
network = "dev-albatross"
sync_mode = "full"

[database]
path = "./tmp/.nimiq3"

[rpc-server]
port = 8650

[log]
level = "debug"

[mempool]

[validator]
validator_address = "NQ43 8U7V C3UE VRGS 8HE7 C43P DEJ3 V0XJ 6NPN"
signing_key_file = "./tmp/.nimiq3/signing_key.dat"
voting_key_file = "./tmp/.nimiq3/voting_key.dat"
fee_key_file = "./tmp/.nimiq3/fee_key.dat"
signing_key = "b0e7a4ddb0d40912348723eacb26f98755a2be3054d78ee295a46382c44a8032"
voting_key = "bccb4ebea1cf72400afed052f9b7ba318f3fff33e6651a9aa9385e8eee80b596ebf23f132524b21f69d694aa092484a703dde646bf8e547df4e2dae20198ad6d461557502227b7f82ef1baae6d4bc0d05fc676edb9b505a5183b1c2de7bc00"
automatic_reactivate = true
