name = "dev-albatross"
network = "DevAlbatross"
timestamp = "2023-03-22T00:00:00.000+00:00"
vrf_seed = "e8c7f2f3935da9ca39419aa7d2cc90817245f75e58cc543f2b9478766308e8a50fffccb09e2df3546f5a0c0059d73a506c48fa2b546f15b511d0f7a63f0ee20cd510a87f520e26478bb687ca31a08db8b02921f9a22e32a790c07f16dbdf4501"
parent_hash = "d7b808129639b27cfc6c3245111db37ba85099496c66ffcb14a6754eb5a1007f"
parent_election_hash = "264aaf8a4f9828a76c550635da078eb466306a189fcc03710bee9f649c869d12"
block_number = 21601

[[validators]]
validator_address = "NQ64 9F95 QT38 4JXR G5XK 52XJ A9XJ M8LD GUEK"
signing_key       = "d4371255f52d6c4080ad45ae00e377989084d3043de0ee60fe982c45bbc1f75b"
voting_key        = "ab10bba0350d7c9ab7377848fa0c5c86d769724368043d1918ea9bc0e30be6815979e0e4047097f164a4622d3ba28ae4577d1f96b7324ac17bde1cd0187c12702303c25cfae41af82250022f5d64292e02544cb5ea3e8123509168e1f5e5008a4490f051d9345882216d042bbe5173f91a4e393aedbe632aba9bca56f5e3371004724b8f6769fb3212d5c50f05c64ed35e6cef250ee54ddcc60bc060cd8f719a618f58b3b7d17b6b45738a9989973b06a1c4252d435abac0f719c0a08c00db2001e85ff467006808f2ca78f4329e634d51d7933da195a0bac71ceb07bc1481f7535b37d137e7462409c1761a329ad80fa361ce0497bf04dbc84c3f06fcb81d34af6a2b38a6776413401ff1a37c74c2c0d9026cd1506916ab30ca25a580"
reward_address    = "NQ64 9F95 QT38 4JXR G5XK 52XJ A9XJ M8LD GUEK"


[[validators]]
validator_address = "NQ50 M8T2 8U7N 2BNQ CSLD 2251 X9EF 5GVD EY9G"
signing_key       = "babdc6b231aa8a7088edb037897736b11fff4bd1f9fa817888bf1e69c49396ee"
voting_key        = "f0b5e6bd19d4f9039e42f314c7511e140f5510759bd3da33b18c3b534af14284a93ab879be2339a46e8d05becb5d8eab52876a9a299dcadd867a577e33b0ab2391189eaf38ac2bc1473364b19d09981ba2b9b5185d358dc1a3e449054a4a00d6d360072c4421a824a1dc7e542f057a3a58aae83148b416fe32f7b38e3b78fe06d3a704d34067347fff79f0d1ee7221f522d3609a06622f6203dca77a2df73aef648b6071f2dc584c5bc60537b6049cec6f44b6412e41d48a34efe9ee3200f4f7b10a1b9ae998f32febcc77dc877b42c59893c624960c6b17346c68a3af9791af56a3bac3577bead0e672db5abf44e744522230517703217ab25bd86ebfa01534bffdafc18a2647e3a65851b319f3cc9b79fa5a112f237e615e9f3cb981"
reward_address    = "NQ50 M8T2 8U7N 2BNQ CSLD 2251 X9EF 5GVD EY9G"


[[validators]]
validator_address = "NQ43 8U7V C3UE VRGS 8HE7 C43P DEJ3 V0XJ 6NPN"
signing_key       = "fefbcec12545aed3b62812e673f5356720fea039aa1ae301865a0ef45e959535"
voting_key        = "1380ecfffde2551f8260cb4633e80d52c59f6fafbd8754fbfdb3f57354bcece36a432c496737151d9df567a375aaa730e162396784881d77636aabb2af54acd17def9886e141731e21ade9d6d678074b29f47b2a3d9d8b81f92b63cf827500a3e3866bf2cab9317bbad62f9c559f5ebc905503ccf3359b6db8958242ac704462fadae57d3f711d4ffd878f4e62957fe8cc50d4ab57791baecf9b979eb67ecbf2fa04e00a078a247b60e9c3478de250e86a28c04064809ba4d6f8c8226f001bb59150edebb6d1c0f4b959326861595050d41e312ff68aaaed41dab494c83bb26d76818604f2a1f052b7e4087a1a87194159bd1e6af64b20feb4e016512652f3c71944f93e5631a7e931cd523d27e09f5a9dd2af5207465911063aa7ab01"
reward_address    = "NQ43 8U7V C3UE VRGS 8HE7 C43P DEJ3 V0XJ 6NPN"


[[validators]]
validator_address = "NQ28 RABB NVRL TMD0 KST7 QFJ6 QTNP 72QJ 74J2"
signing_key       = "397d5cde4780b5711e3e842e7b16081be224b73b5477ef6dc6c0ac676b64dc4b"
voting_key        = "0b683d145e385ad2c4ddf592d1a7f2ef405628d3d444c92a7f8e2acdfd1838f2952f0a62fcdef99d028aec7bad885267c90661321546cb6811522d4e1870c944cfa760179250ff09483c57c62b7a36d3ab369a903d0fb00d18e2e9e39ae5006385acef9ed109aff666e18c234a63f9bc2f414fdffd3469e6e1d5a5c9aef524a1954be2fb19ec0f08821ad79e7c01874b75ed4ce05febd7db97236d110d25c499bd96244b4f361ad66ef3b852a38888dbc290c97af9c943cdc7dde6215a01728210b69918bd569fbddff36a2578b6001d634681c82741ebbaeb00a3a490b16ca89e3a4b125d5a7e5cbfed7a8c9d3472dd0e85a17f501508aa80cb4da170efa246fa64e0b79a01ca15bf7c52b6011515b51d1133330af07dc6bd292c0f81"
reward_address    = "NQ28 RABB NVRL TMD0 KST7 QFJ6 QTNP 72QJ 74J2"

[[stakers]]
staker_address = "NQ64 9F95 QT38 4JXR G5XK 52XJ A9XJ M8LD GUEK"
balance = 1_000_000
delegation = "NQ64 9F95 QT38 4JXR G5XK 52XJ A9XJ M8LD GUEK"

[[basic_accounts]]
address = "NQ64 9F95 QT38 4JXR G5XK 52XJ A9XJ M8LD GUEK"
balance = 10_000_000_00000


[[stakers]]
staker_address = "NQ50 M8T2 8U7N 2BNQ CSLD 2251 X9EF 5GVD EY9G"
balance = 1_000_000
delegation = "NQ50 M8T2 8U7N 2BNQ CSLD 2251 X9EF 5GVD EY9G"

[[basic_accounts]]
address = "NQ50 M8T2 8U7N 2BNQ CSLD 2251 X9EF 5GVD EY9G"
balance = 10_000_000_00000


[[stakers]]
staker_address = "NQ43 8U7V C3UE VRGS 8HE7 C43P DEJ3 V0XJ 6NPN"
balance = 1_000_000
delegation = "NQ43 8U7V C3UE VRGS 8HE7 C43P DEJ3 V0XJ 6NPN"

[[basic_accounts]]
address = "NQ43 8U7V C3UE VRGS 8HE7 C43P DEJ3 V0XJ 6NPN"
balance = 10_000_000_00000


[[stakers]]
staker_address = "NQ28 RABB NVRL TMD0 KST7 QFJ6 QTNP 72QJ 74J2"
balance = 1_000_000
delegation = "NQ28 RABB NVRL TMD0 KST7 QFJ6 QTNP 72QJ 74J2"

[[basic_accounts]]
address = "NQ28 RABB NVRL TMD0 KST7 QFJ6 QTNP 72QJ 74J2"
balance = 10_000_000_00000

[[basic_accounts]]
address = "NQ37 7C3V VMN8 FRPN FXS9 PLAG JMRE 8SC6 KUSQ"
balance = 10_000_000_00000

[[basic_accounts]]
address = "NQ87 HKRC JYGR PJN5 KQYQ 5TM1 26XX 7TNG YT27"
# private_key = "3336f25f5b4272a280c8eb8c1288b39bd064dfb32ebc799459f707a0e88c4e5f"
balance = 10_000_000_00000
