[network]
listen_addresses = [
  "/ip4/127.0.0.1/tcp/8443/ws",
]
seed_nodes = [
  { address = "/ip4/127.0.0.1/tcp/8445/ws" },
  { address = "/ip4/127.0.0.1/tcp/8446/ws" },
  { address = "/ip4/127.0.0.1/tcp/8447/ws" },
]
allow_loopback_addresses = true
desired_peer_count = 1
peer_key_file = "./tmp/.nimiq1/peer_key.dat"

[consensus]
network = "dev-albatross"
sync_mode = "full"

[database]
path = "./tmp/.nimiq1"

[rpc-server]
port = 8648

[log]
level = "debug"

[mempool]

[validator]
validator_address = "NQ64 9F95 QT38 4JXR G5XK 52XJ A9XJ M8LD GUEK"
signing_key_file = "./tmp/.nimiq1/signing_key.dat"
voting_key_file = "./tmp/.nimiq1/voting_key.dat"
fee_key_file = "./tmp/.nimiq1/fee_key.dat"
signing_key = "f32b75bfe2bf091ceb15b08742abb75d0256c5176318fdd5219742b67ba91dfe"
voting_key = "ea7306d61cbb5cea20ccbb3b777fd9f1c21124b856594b5f30d02e3fc1b5dce4fd61ffd39904abfb1738ac9d325179cca65525e0285131ccd52eb55b6552a3986ffbcc97b111c852832813ab7ade1044c72c5387c2f7bd576534e9b1e70200"
automatic_reactivate = true
