[network]
listen_addresses = [
  "/ip4/127.0.0.1/tcp/8447/ws",
]
seed_nodes = [
  { address = "/ip4/127.0.0.1/tcp/8443/ws" },
  { address = "/ip4/127.0.0.1/tcp/8445/ws" },
  { address = "/ip4/127.0.0.1/tcp/8446/ws" },
]
allow_loopback_addresses = true
desired_peer_count = 1
peer_key_file = "./tmp/.nimiq4/peer_key.dat"

[consensus]
network = "dev-albatross"
sync_mode = "full"

[database]
path = "./tmp/.nimiq4"

[rpc-server]
port = 8651

[log]
level = "debug"

[mempool]

[validator]
validator_address = "NQ28 RABB NVRL TMD0 KST7 QFJ6 QTNP 72QJ 74J2"
signing_key_file = "./tmp/.nimiq4/signing_key.dat"
voting_key_file = "./tmp/.nimiq4/voting_key.dat"
fee_key_file = "./tmp/.nimiq4/fee_key.dat"
signing_key = "b4a92daa43d68aad83f51b41a412f4204702954ad1477a4e6a8578f9aa88c55b"
voting_key = "0ac9ef793c25d400b4aa88eaa79b057a8bb9a110013d061d96dd7cc185918d55312e6b1f5477e94ca065a22e17efd325e6ba082736a25f1c9daca4cd7ccd27709189c8cd39feb723774911809ada8ec4c40db111501602d3459f95860cf800"
automatic_reactivate = true
