[network]
listen_addresses = [
  "/ip4/127.0.0.1/tcp/8445/ws",
]
seed_nodes = [
  { address = "/ip4/127.0.0.1/tcp/8443/ws" },
  { address = "/ip4/127.0.0.1/tcp/8446/ws" },
  { address = "/ip4/127.0.0.1/tcp/8447/ws" },
]
allow_loopback_addresses = true
desired_peer_count = 1
peer_key_file = "./tmp/.nimiq2/peer_key.dat"

[consensus]
network = "dev-albatross"
sync_mode = "full"

[database]
path = "./tmp/.nimiq2"

[rpc-server]
port = 8649

[log]
level = "debug"

[mempool]

[validator]
validator_address = "NQ50 M8T2 8U7N 2BNQ CSLD 2251 X9EF 5GVD EY9G"
signing_key_file = "./tmp/.nimiq2/signing_key.dat"
voting_key_file = "./tmp/.nimiq2/voting_key.dat"
fee_key_file = "./tmp/.nimiq2/fee_key.dat"
signing_key = "df6ac780905ea7fef5337d0a61f55dacf2f26d8d90269db41949117562de31fd"
voting_key = "678f533ab3ded484dfd0bbc80ce8d90033cff4498a010f01854fee958b35ce954bb492b81d80e9be181029c249f370ca79b4acd61afb32310aecf15a689324ecba9f42c4293d8a56e4d481a082285a80641f143ce9cc42b633dfc312e06200"
automatic_reactivate = true
